### ISSUE TITLE
Erratic but very common timeout exception

### ISSUE THREAD

**Issue by JakeCowton** [iammrhelo/InstagramCrawler#10]
Frequently get this error when storing captions. Doesn't seem to be an issue when just taking images.
```
Traceback (most recent call last):
  File "instagramcrawler.py", line 341, in <module>
    main()
  File "instagramcrawler.py", line 337, in main
    authentication=args.authentication)
  File "instagramcrawler.py", line 114, in crawl
    self.click_and_scrape_captions(number)
  File "instagramcrawler.py", line 221, in click_and_scrape_captions
    EC.presence_of_element_located((By.TAG_NAME, "time"))
  File "/home/jake/.virtualenvs/insta/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by sarahmichele** [comment]
I am having a timeout exception as well- but at a slightly different spot.  Mine is not erratic- I have not gotten the code to work for me at all.

  File "C:/Users/QS-2 SARAH/Desktop/IG/IGcrawler.py", line 360, in <module>
    main()
  File "C:/Users/QS-2 SARAH/Desktop/IG/IGcrawler.py", line 356, in main
    authentication=args.authentication)
  File "C:/Users/QS-2 SARAH/Desktop/IG/IGcrawler.py", line 119, in crawl
    self.scroll_to_num_of_posts(number)
  File "C:/Users/QS-2 SARAH/Desktop/IG/IGcrawler.py", line 171, in scroll_to_num_of_posts
    (By.CSS_SELECTOR, CSS_LOAD_MORE))
  File "C:\Users\QS-2 SARAH\Anaconda2\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException
