### ISSUE TITLE
why can't I get the photo links?

### ISSUE THREAD

**Issue by zhaobr340104** [iammrhelo/InstagramCrawler#12]
Hi! I typed 
python instagramcrawler.py -q #breakfast -n 50
Then the firefox worked. But  the crawler program showed:
posts: 61650050, number: 50
Saving...
Saving to directory: E:/ins\breakfast.hashtag
Scraping photo links...
Number of photo_links: 33
?[FDownloading 1 images to
Traceback (most recent call last):
  File "instagramcrawler.py", line 342, in <module>
    main()
  File "instagramcrawler.py", line 338, in main
    authentication=args.authentication)
  File "instagramcrawler.py", line 133, in crawl
    self.download_and_save(dir_prefix, query, crawl_type)
  File "instagramcrawler.py", line 294, in download_and_save
    urlretrieve(photo_link, filepath)
  File "C:\Python27\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\Python27\lib\urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 443, in open_https
    h.endheaders(data)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 363, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 611, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:661)

So why can't I download them?

**Comment by zhaobr340104** [comment]
The Regular Expression of the photo links seems to be wrong
