### ISSUE TITLE
Timeout exception

### ISSUE THREAD

**Issue by sarahmichele** [iammrhelo/InstagramCrawler#13]
I am getting the following error.  The CSS selector needs to be updated from what is in the code (it is now "a._1cr2e _epyes"), but that still does not solve it for me.

Any insights much appreciated! 

Traceback (most recent call last):
  File "C:/Users/QS-2 SARAH/Desktop/IG/IGcrawler.py", line 360, in <module>
    main()
  File "C:/Users/QS-2 SARAH/Desktop/IG/IGcrawler.py", line 356, in main
    authentication=args.authentication)
  File "C:/Users/QS-2 SARAH/Desktop/IG/IGcrawler.py", line 119, in crawl
    self.scroll_to_num_of_posts(number)
  File "C:/Users/QS-2 SARAH/Desktop/IG/IGcrawler.py", line 171, in scroll_to_num_of_posts
    (By.CSS_SELECTOR, CSS_LOAD_MORE))
  File "C:\Users\QS-2 SARAH\Anaconda2\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException

**Comment by sarahmichele** [comment]
**This issue is solved. The CSS_LOAD_MORE should be "a._1cr2e._epyes"

**Comment by aarzamasov** [comment]
thank you @sarahmichele  - thats works!
