### ISSUE TITLE
'geckodriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by dontsovcmc** [iammrhelo/InstagramCrawler#15]
Please add info, that user should install geckodriver to PC and add path to PATH. Thanks!

`Query account 'instagram', download 20 photos and their captions
Traceback (most recent call last):
  File "instagramcrawler.py", line 355, in <module>
    main()
  File "instagramcrawler.py", line 345, in main
    crawler = InstagramCrawler(headless=args.headless)
  File "instagramcrawler.py", line 67, in __init__
    self._driver = webdriver.Firefox()
  File "C:\Python27\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 142, in __init_                                 _
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH                                 .
`

**Comment by jopasserat** [comment]
Check the commands in [`.travis.yml`](https://github.com/iammrhelo/InstagramCrawler/blob/master/.travis.yml):

https://github.com/iammrhelo/InstagramCrawler/blob/ba8086b0859a0bcd54347712bfb5305091a2c396/.travis.yml#L11-L14

**Comment by yakupad** [comment]
try this -> brew install geckodriver

**Comment by markusMM** [comment]
Thus, geckodriver needs to be in PATH?

Thou, it does not matter, where the geckodriver in my system path actually is (as long as it is reachable), right?
