### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by diihfilipe** [iammrhelo/InstagramCrawler#23]
I'm getting this error when i ran that script ( also happens with python comand )

python3 instagramcrawler.py -q '#breakfast' -n 20 -a auth.json
Traceback (most recent call last):
  File "instagramcrawler.py", line 360, in <module>
    main()
  File "instagramcrawler.py", line 350, in main
    crawler = InstagramCrawler(headless=args.headless, firefox_path=args.firefox_path)
  File "instagramcrawler.py", line 72, in __init__
    self._driver.implicitly_wait(10)
  File "/home/mestre/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 719, in implicitly_wait
    'implicit': int(float(time_to_wait) * 1000)})
  File "/home/mestre/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "/home/mestre/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: timeouts

**Comment by carlosb1** [comment]
I have the same error.... I only followed the installation steps in my  Linux Mint 18.3 Sylvia

**Comment by hanbz** [comment]
get the same issue and my os is OS X  so I download the geckodriver in osx version
