### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by L33tH4x0r** [iammrhelo/InstagramCrawler#26]
When running just a basic search on the instagram profile, with `python instagramcrawler.py -q instagram -t photos -n 100 -l` I get the following error:

```
Traceback (most recent call last):
  File "instagramcrawler.py", line 360, in <module>
    main()
  File "instagramcrawler.py", line 356, in main
    authentication=args.authentication)
  File "instagramcrawler.py", line 117, in crawl
    self.scroll_to_num_of_posts(number)
  File "instagramcrawler.py", line 161, in scroll_to_num_of_posts
    self._driver.page_source).group()
AttributeError: 'NoneType' object has no attribute 'group'
```
Any idea on what I'm doing wrong?

phantomjs version 1.9.8
ubuntu 16.04

**Comment by Lusia731** [comment]
I got the same problem.
Any fix idea?

I'm on Mac OS

Thanks

**Comment by leohidalgo** [comment]
+1

**Comment by hongkongrhon** [comment]
+1, on windows

**Comment by fqiu1kpmg** [comment]
+1 on ubuntu 14

**Comment by wwwehr** [comment]
hi guys - I made a pull request to fix this here:
> https://github.com/iammrhelo/InstagramCrawler/pull/27

**Comment by uniqmuz** [comment]
+1, it works on wsl
