### ISSUE TITLE
Firefox path not solve and Need gecko driver executable in path

### ISSUE THREAD

**Issue by santwijaya** [iammrhelo/InstagramCrawler#28]
I try the program and changing path to "C:\Program Files\Mozilla Firefox" in instagramcrawker.py program, but when just run the program i get this message. I use it with Windows 10 and firefox 59. Any Idea o fix this issue?

```
Traceback (most recent call last):
  File "instagramcrawler.py", line 360, in <module>
    main()
  File "instagramcrawler.py", line 350, in main
    crawler = InstagramCrawler(headless=args.headless, firefox_path="C:\Program Files\Mozilla Firefox")
  File "instagramcrawler.py", line 70, in __init__
    self._driver = webdriver.Firefox(firefox_binary=binary)
  File "C:\Users\Santo Wijaya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 142, in __init__
    self.service.start()
  File "C:\Users\Santo Wijaya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

**Comment by markusMM** [comment]
Hey, I have a similar problem...
1st : Did you already install [geckodriver.exe]((https://github.com/mozilla/geckodriver/releases))
and
added it into system settings / system / system variables / Path -> add -> "the path where your geckodriver.exe is"
2nd : If you already have:

Do you have the same problem that it just opens the browser and fails?

I am sure it makes twice as much sense to run this on Ubuntu and with logged in Instagram account!
Since ppl can see Pictures as long as they're not logged in, the machine needs this login to work, right?
