### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by PicaKing** [iammrhelo/InstagramCrawler#4]
Hi
When we run the script in pycharm on windows we get this exception:

```

C:\Python27\python.exe C:/Users/Vahid/PycharmProjects/instagram/instagramcrawler.py -q instagram -t photos -c -n 100
Number to crawl 100
Traceback (most recent call last):
  File "C:/Users/Vahid/PycharmProjects/instagram/instagramcrawler.py", line 314, in main
    crawler.browse(args.query,args.type).crawl(args.number,args.caption).save()
  File "C:/Users/Vahid/PycharmProjects/instagram/instagramcrawler.py", line 127, in crawl
    self.captions = self._crawl_captions()
  File "C:/Users/Vahid/PycharmProjects/instagram/instagramcrawler.py", line 234, in _crawl_captions
    EC.presence_of_element_located((By.CSS_SELECTOR,CSS_RIGHT_ARROW))
  File "C:\Python27\lib\site-packages\selenium\webdriver\support\wait.py", line 81, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:  
```

How can we solve the problem?

**Comment by tzuhsial** [comment]
Just pushed a new version, didn't do much testing though
