### ISSUE TITLE
error

### ISSUE THREAD

**Issue by oceanMIH** [iammrhelo/InstagramCrawler#5]
windows7 64bit, running the following command:
python instagramcrawler.py -q 'nude_yogagirl' -n 20

output is:
d:\python\InstagramCrawler-master>python instagramcrawler.py -q 'nude_yogagirl' -n 20 Traceback (most recent call last):
  File "instagramcrawler.py", line 297, in <module>
    main()
  File "instagramcrawler.py", line 291, in main
    crawler = InstagramCrawler()
  File "instagramcrawler.py", line 58, in __init__
    self._driver = webdriver.Firefox()
  File "D:\Program Files\Python361\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 152, in __init__
    keep_alive=True)
  File "D:\Program Files\Python361\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Program Files\Python361\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 185, in start_session

    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Program Files\Python361\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Program Files\Python361\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of apabilities

**Comment by tzuhsial** [comment]
Hi, I did not encounter any problems while attempting to reproduce your query.
After googling, this seems to be a somewhat weird bug at selenium
https://github.com/SeleniumHQ/selenium/issues/3884

**Comment by gseek27** [comment]
@oceanMIH  It's probably related to the location of your Firefox executable. Try this:

https://github.com/SeleniumHQ/selenium/issues/3884#issuecomment-302924274

**Comment by oceanMIH** [comment]
Thanks a lot for your suggestions: but I don't have Firefox installed, instead I have IE and chrome installed on my windows 7 machine.

**Comment by gseek27** [comment]
You'll still need to specify the path to the Chromedriver executable, like this (in Mac):

driver = webdriver.Chrome("/usr/local/bin/chromedriver")
