### ISSUE TITLE
Cannot crawl data

### ISSUE THREAD

**Issue by huibrian** [iammrhelo/InstagramCrawler#6]
D:\Development\python\InstagramCrawler-master>python instagramcrawler.py -q daniel.hoi23s -c -n 100
dir_prefix: ./data/, query: daniel.hoi23s, crawl_type: photos, number: 100, caption: True
posts: 394, number: 100
Scraping photo links...
Number of photo_links: 27
Scraping captions...
Traceback (most recent call last):
  File "instagramcrawler.py", line 297, in <module>
    main()
  File "instagramcrawler.py", line 293, in main
    caption=args.caption)
  File "instagramcrawler.py", line 85, in crawl
    self.click_and_scrape_captions(number)
  File "instagramcrawler.py", line 161, in click_and_scrape_captions
    FIREFOX_FIRST_POST_PATH).click()
  File "C:\Users\aaaaa\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\aaaaa\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\aaaaa\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "C:\Users\aaaaa\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message:

============================================

geckodriver.log:
1496170001211	geckodriver	INFO	Listening on 127.0.0.1:64773
1496170003300	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1496170004239	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:671 < startup()@resource://gre/modules/AddonManager.jsm:834 < startup()@resource://gre/modules/AddonManager.jsm:3129 < observe()@resource://gre/components/addonManager.js:65
JavaScript error: resource://gre/modules/AddonManager.jsm, line 1657: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
1496170009047	Marionette	INFO	Listening on port 64780
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2570: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
1496170009378	Marionette	WARN	TLS certificate errors will be ignored for this session
JavaScript error: resource://gre/modules/FileUtils.jsm, line 70: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]

**Comment by tzuhsial** [comment]
Hi, this seems also to be a selenium bug

**Comment by huibrian** [comment]
thanks man. how can I fix it for this case?

**Comment by huibrian** [comment]
do you have such issues as well?

**Comment by tzuhsial** [comment]
Sorry for the late reply...
I didn't really crawl a lot of stuff with the code, so to be honest, I could miss a lot issues.

Perhaps setting try & catch will help?
